wsp/wsp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wspsite.urls')) # Add this line to include the hafapp urls.py file
]

wsp/wspsite/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('pricing', views.pricing, name='pricing'),
    path('productinfo', views.productinfo, name='productinfo'),
    path('faqs', views.faqs, name='faqs'),
    path('about', views.about, name='about'),
    path('order', views.order, name='order'),
    path('small_order', views.small_order, name='small_order'),
    path('med_order', views.med_order, name='med_order'),
    path('ent_order', views.ent_order, name='ent_order'),
    path('thankyou', views.thankyou, name='thankyou'),
]

wsp/wspsite/models.py
from django.db import models

class OrderData(models.Model):
   responsibleParty = models.CharField(max_length=200)
   cases = models.CharField(max_length=200)

   def __str__(self):
       return f'{self.responsibleParty} : {self.cases}'

wsp/wspsite/forms.py
from django import forms
from .models import OrderData
from django.urls import reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Field
from django.core.validators import RegexValidator

class OrderDataForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_action = reverse_lazy('thankyou')
        self.helper.form_method = 'get'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-4'
        self.helper.field_class = 'col-lg-6'
        self.helper.layout = Layout(
            'responsibleParty',
            'email',
            'phone',
            'cases',
            'address1',
            'address2',
            'city',
            'state',
            'comments'
        )
        self.helper.add_input(Submit('submit', 'Submit Order'))
        self.helper.attrs['autocomplete'] = 'off'
  
        for field in self.fields.values():
            field.widget.attrs['title'] = ''

    STATES = [
        ('', 'Choose...'),
        ('AL', 'Alabama'),
        ('AK', 'Alaska'),
        ('AZ', 'Arizona'),
        ('AR', 'Arkansas'),
        ('CA', 'California'),
        ('CO', 'Colorado'),
        ('CT', 'Connecticut'),
        ('DE', 'Delaware'),
        ('FL', 'Florida'),
        ('GA', 'Georgia'),
        ('HI', 'Hawaii'),
        ('ID', 'Idaho'),
        ('IL', 'Illinois'),
        ('IN', 'Indiana'),
        ('IA', 'Iowa'),
        ('KS', 'Kansas'),
        ('KY', 'Kentucky'),
        ('LA', 'Louisiana'),
        ('ME', 'Maine'),
        ('MD', 'Maryland'),
        ('MA', 'Massachusetts'),
        ('MI', 'Michigan'),
        ('MN', 'Minnesota'),
        ('MS', 'Mississippi'),
        ('MO', 'Missouri'),
        ('MT', 'Montana'),
        ('NE', 'Nebraska'),
        ('NV', 'Nevada'),
        ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'),
        ('NY', 'New York'),
        ('NC', 'North Carolina'),
        ('ND', 'North Dakota'),
        ('OH', 'Ohio'),
        ('OK', 'Oklahoma'),
        ('OR', 'Oregon'),
        ('PA', 'Pennsylvania'),
        ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'),
        ('SD', 'South Dakota'),
        ('TN', 'Tennessee'),
        ('TX', 'Texas'),
        ('UT', 'Utah'),
        ('VT', 'Vermont'),
        ('VA', 'Virginia'),
        ('WA', 'Washington'),
        ('WV', 'West Virginia'),
        ('WI', 'Wisconsin'),
        ('WY', 'Wyoming'),
    ]

    responsibleParty = forms.CharField(
        label = "Responsibility Party Name",
        max_length = 200,
        required = False,
    )

    email = forms.EmailField(
        label = "Email Address",
        max_length = 200,
        required = False,
    )

    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
    )

    phone = forms.IntegerField(
        validators=[phone_regex],
        label = "Phone",
        required = False,
        widget=forms.TextInput(attrs={'placeholder': '+(515) 555-1212'}),
    )

    cases = forms.IntegerField(
        label = "Number of Cases",
        min_value = 25,
        required = False,
    )

    address1 = forms.CharField(
        label = "Address 1",
        max_length = 200,
        required = False,
    )

    address2 = forms.CharField(
        label = "Address 2",
        max_length = 200,
        required = False,
    )

    city= forms.CharField(
        label = "City",
        max_length = 200,
        required = False,
    )

    state = forms.TypedChoiceField(
        label = "States",
        choices = STATES,
        required = False,
    )

    comments = forms.CharField(
        label = "Comments",
        max_length=200,
        widget=forms.Textarea(attrs={'rows': 4, 'cols': 50})
    )

wsp/wspsite/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from .models import OrderData
from .forms import OrderDataForm
import requests
import datetime

# Create your views here.
def home(request):
    return render(request, 'home.html')

def pricing(request):
    return render(request, 'partials/pricing.html')

def productinfo(request):
    return render(request, 'partials/productinfo.html')

def faqs(request):
    return render(request, 'partials/faqs.html')

def about(request):
    return render(request, 'partials/about.html')

def order(request):
 return render(request, 'partials/order.html')

def small_order(request):
    if request.method == 'POST':
        form = OrderDataForm(request.POST)
        if form.is_valid():
            form.field_order = ['responsibleParty', 'email', 'phone', 'cases', 'address1', 'address2', 'city', 'state', 'comments']
            return HttpResponseRedirect('/thankyou')
    else:
            form = OrderDataForm()

    return render(request, 'partials/small_order.html', {'form': form})

def med_order(request):
    if request.method == 'POST':
        form = OrderDataForm(request.POST)
        if form.is_valid():
            form.field_order = ['responsibleParty', 'email', 'phone', 'cases', 'address1', 'address2', 'city', 'state', 'comments']
            return HttpResponseRedirect('/thankyou')
    else:
            form = OrderDataForm()

    return render(request, 'partials/med_order.html', {'form': form})

def ent_order(request):
    if request.method == 'POST':
            form = OrderDataForm(request.POST)
            if form.is_valid():
                form.field_order = ['responsibleParty', 'email', 'phone', 'cases', 'address1', 'address2', 'city', 'state', 'comments']
                return HttpResponseRedirect('/thankyou')
    else:
            form = OrderDataForm()

    return render(request, 'partials/ent_order.html', {'form': form})

def thankyou(request):
    entOrderData = request.GET
    return render(request, 'partials/thankyou.html', {'entOrderData': entOrderData})

# class thankyou(TemplateView):
#     template_name = 'partials/thankyou.html'

#     def post(self, request):
#         form = OrderDataForm(request.POST)
#         entFormData = {}
#         if form.is_valid():
#             entFormData = form.cleaned_data("post")

#         args = {'form': form, "context": entFormData}
#         return render(request, self.template_name, args)

wsp/wspsite/templates/home.html
{% load django_bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>My Web Page</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script>
      $(document).ready(function() {
          var path = window.location.pathname;
          var page = path.split("/").pop();

          var navElements = document.querySelectorAll('.nav-link');

          for (var i = 0; i < navElements.length; i++) {
              var navItem = navElements[i];
              var link = navItem.getAttribute('href');

              if (link.indexOf(page) !== -1) {
                  navItem.classList.add('active');
              }
          }

          $('#id_phone').mask('+1 (000) 000-0000');
          $("#id_email").validate({
            rules: {
              field: {
                required: true,
                email: true
              }
            }
          });
      });
  </script>
  <style>
    .bg-home {
      background-image: url("{% static 'images/home_hero.jpg' %}");
      background-size: cover;
      background-position: center;
    }

    .text-inverted {
      filter: invert(1) grayscale(100%) brightness(200%);
  }

  .nav-pills .nav-link.active, .nav-pills .show>.nav-link {
    color: white;
    background-color: green;
}
  }
  </style>
 
</head>
<body>
    {% include 'partials/header.html' %}

    <!-- Include your main content here -->
  <main class="px-0" height="90vh">
    {% block content %}
        <div class="px-4 py-5 my-5 text-center bg-home" width="150px">
          {% load static %}
            <h1 class="display-5 fw-bold text-body-emphasis text-inverted">A Taste of Summer
            </h1>
            <div class="col-lg-6 mx-auto text-inverted">
              <p class="lead mb-4">Our Watermelon Seltzer is not just a beverage; it’s a taste of summer in every can. Crafted with natural watermelon flavor, it delivers a refreshing, crisp taste that’s perfect for scorching summer days or when you’re simply yearning for a sip of sunshine.
              </p>
              <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <a href="/pricing" id="linkPricing" name="linkPricing" class="btn btn-primary btn-lg px-4 gap-3">Order Now</a>
              </div>
            </div>
          </div>

    {% endblock %}
    
  </main>

    <!-- Include your footer content here -->
    <footer>
        {% include 'partials/footer.html' %}
    </footer>

</body>
</html>

wsp/wspsite/templates/partials/about.html
{% extends "home.html" %} {% block content %}
<section>
  <main>
    <div
      class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light"
    >
      <div class="col-md-12">
        <h1 class="display-4 fw-normal">Welcome to “XThirst”</h1>
        <p class="lead fw-normal">
          At XThirst, we believe that every sip should be an escape to
          sun-kissed beaches, even if you’re just lounging on your couch. Our
          watermelon-infused hard seltzers are the ultimate ode to summer,
          blending the juiciness of real watermelons with the effervescence of
          pure refreshment. Dive in and discover the taste of endless summer in
          every can.
        </p>
      </div>
      <div class="product-device shadow-sm d-none d-md-block"></div>
      <div
        class="product-device product-device-2 shadow-sm d-none d-md-block"
      ></div>
    </div>

    <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
      <div
        class="bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden"
      >
        <div class="my-3 py-3">
          <h2 class="display-5">Why XThirst?</h2>
          <p class="fs-5">
            Crafted with Love: Our master brewers handpick the ripest
            watermelons, capturing their essence in every batch. Each can is a
            labor of love, infused with the spirit of sun-soaked afternoons.
          </p>
          <p class="fs-5">
            Authentic Flavor: No shortcuts here! We’ve perfected the delicate
            balance of sweet and refreshing watermelon flavor. Close your eyes,
            take a sip, and let the waves of nostalgia wash over you.
          </p>
          <p class="fs-5">
            Zero Guilt, All Pleasure: With only 100 calories per can and zero
            added sugar, XThirst lets you indulge guilt-free. It’s like a
            guilt-free beach vacation—minus the sand in your shoes.
          </p>
        </div>
      </div>
      <div
        class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden"
      >
        <div class="my-3 p-3">
          <h2 class="display-5">Our Seltzer Lineup:</h2>
          <p class="fs-4">
            <strong>Watermelon Seltzer Drink:</strong> The OG. Bursting with
            juicy watermelon goodness, it’s like biting into a slice of summer.
            Perfect for lazy picnics, rooftop parties, or simply because life
            deserves a refreshing twist. 🍉☀️
          </p>
          <p class="fs-4">
            <strong>Tropical Splash:</strong> Watermelon meets pineapple, with a
            hint of coconut. Close your eyes, and suddenly you’re sipping under
            a palm tree. 🌴🍍🥥
          </p>
          <p class="fs-4">
            <strong>Sunset Serenade:</strong> Watermelon blended with blood
            orange—because sunsets taste better with a citrus twist. Share it
            with friends or keep it all to yourself; we won’t judge. 🌅🍊
          </p>
        </div>
      </div>
    </div>
    <div class="w-100 my-md-3 ps-md-3">
      <div
        class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden"
      >
        <div class="my-3 py-3">
          <h2 class="display-5">Join the XThirst Community:</h2>

          Follow us on social media: {% load static %}
          <div class="d-flex justify-content-center">
            <img src="{% static 'images/social.png' %}" alt="" width="250px" />
          </div>
        </div>
      </div>
    </div>
    <div class="w-100 my-md-3 ps-md-3">
      <div
        class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden"
      >
        <div class="my-3 py-3">
          <h2 class="display-5">Where to Find Us:</h2>
          <p class="h5">
            XThirst Seltzers are available at your local beachside bodega,
            surf shops, and select rooftop bars.
          </p>
        </div>
      </div>
    </div>
  </main>
  {% endblock %}
</section>

wsp/wspsite/templates/partials/ent_order.html
{% extends "home.html" %} {% block content %} {% load crispy_forms_tags %}
<section>
  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal">Enterpise Order Form</h1>
    <p class="fs-5 text-muted">
      Use this form to order more than 25 cases of our product. We will contact you. Thank you for your business.
    </p>
  </div>
  <div class="container justify-content-center">
      {% csrf_token %}
      {% crispy form %}
      <script>
        document.getElementById("id_cases").min = 25;
        document.getElementById("id_cases").max = 100;
      </script>
  </div>
</section>
{% endblock %}

wsp/wspsite/templates/partials/faqs.html
{% extends "home.html" %}
{% block content %}
<section>
    <div class="row g-5">
        <div class="col-md-8">
            <div class="position-relative overflow-hidden p-2 m-md-3 text-center bg-light">
                <div class="col-md-12">
                  <h1 class="display-4 fw-normal">Frequently Asked Questions</h1>
                  <p class="lead fw-normal">“Sip, Savor, and Watermelon Wonders: Your Watermelon Seltzer Questions Answered!” 🍉🥂</p>
                </div>
              </div>

          <article class="blog-post p-5">
            <h2 class="blog-post-title">Is watermelon hard seltzer made from real watermelons?</h2>
            <p>While we’d love to say our seltzers are freshly squeezed from watermelons, the truth is they’re crafted with love and a dash of imagination. 🍉</p>
            <hr>
            <h2 class="blog-post-title">Can I use watermelon hard seltzer as sunscreen?</h2>
            <p>As much as we’d like to claim SPF 50 protection, our seltzers are best enjoyed in a chilled glass, not slathered on your skin. 😎</p>
            <hr>
            <h2 class="blog-post-title">Does watermelon seltzer make you dance better?</h2>
            <p>We can’t guarantee dance moves, but we’ve seen some impressive watermelon-inspired twirls after a can or two. 💃</p>
            <hr>
            <h2 class="blog-post-title">How many watermelon seltzers can I drink before turning into an actual watermelon?</h2>
            <p>We recommend moderation, but rest assured, transformation into a fruit is unlikely. 🤔</p>
            <hr>
            <h2 class="blog-post-title">Can I mix watermelon seltzer with tequila for a wild party?</h2>
            <p>While we don’t endorse wild parties (wink), a splash of tequila might just turn your watermelon seltzer into a fiesta. 🎉</p>
            <hr>
          </article>
        </div>
    
        <div class="col-md-4">
          <div class="position-sticky" style="top: 2rem;">
            <div class="p-4">
              <h4 class="fst-italic">FAQ Archives</h4>
              <ol class="list-unstyled mb-0">
                <li><a href="#">March 2021</a></li>
                <li><a href="#">February 2021</a></li>
                <li><a href="#">January 2021</a></li>
                <li><a href="#">December 2020</a></li>
                <li><a href="#">November 2020</a></li>
                <li><a href="#">October 2020</a></li>
                <li><a href="#">September 2020</a></li>
                <li><a href="#">August 2020</a></li>
                <li><a href="#">July 2020</a></li>
                <li><a href="#">June 2020</a></li>
                <li><a href="#">May 2020</a></li>
                <li><a href="#">April 2020</a></li>
              </ol>
            </div>
    
            <div class="p-4">
              <h4 class="fst-italic">Other FAQs Resources</h4>
              <ol class="list-unstyled">
                <li><a href="#">GitHub</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
              </ol>
            </div>
          </div>
        </div>
      </div>
{% endblock %}
</section>

wsp/wspsite/templates/partials/footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="home" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="productinfo" class="nav-link px-2 text-body-secondary">Product Information</a></li>
      <li class="nav-item"><a href="pricing" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="faqs" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="about" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">© 2024 Jeremy Lankford.</p>
  </footer>

wsp/wspsite/templates/partials/header.html
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <a href="/" class="d-flex align-items-left mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
          {% load static %}
          <img class="d-block mx-auto mb-4" src="{% static 'images/logo.png' %}" alt="" width="250px">
        </a>
      </div>
      <div class="col-9">
          <ul class="nav nav-pills justify-content-end">
            <li class="nav-item"><a href="home" class="nav-link" aria-current="page">Home</a></li>
            <li class="nav-item"><a href="productinfo" class="nav-link">Product Information</a></li>
            <li class="nav-item"><a href="pricing" class="nav-link">Pricing</a></li>
            <li class="nav-item"><a href="faqs" class="nav-link">FAQs</a></li>
            <li class="nav-item"><a href="about" class="nav-link">About</a></li>
          </ul>
          {% load static %}
          <div class="d-flex justify-content-end">
              <img src="{% static 'images/social.png' %}" alt="" width="250px">
          </div>
      </div>
</div>
  </header>

wsp/wspsite/templates/partials/med_order.html
{% extends "home.html" %} {% block content %} {% load crispy_forms_tags %}
<section>
  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal">Medium Business Order Form</h1>
    <p class="fs-5 text-muted">
      Use this form for 13 -25  cases of our product. We will contact you. Thank you for your business.
    </p>
  </div>
  <div class="container justify-content-center">
    {% csrf_token %}
    {% crispy form %}
    <script>
      document.getElementById("id_cases").min = 13;
      document.getElementById("id_cases").max = 25;
    </script>
  </div>
</section>
{% endblock %}

wsp/wspsite/templates/partials/order.html
{% extends "home.html" %}
{% block content %}
    <section>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">Order Form</h1>
            <p class="fs-5 text-muted">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
        </div>
        <form action="/thankyou" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <h1>{{ form.tier1_value.label_tag }}</h1>
        </div>
        <div class="mb-3">
            <label for="responsibleParty" class="form-label">Responsible Party:</label>
            <input type="text" class="form-control" id="responsibleParty">
        </div>
        <div class="mb-3">
            <label for="deliveryAddress" class="form-label">Delivery Address:</label>
            <input type="text" class="form-control" id="deliveryAddress">
        </div>
        <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="callVerify">
        <label class="form-check-label" for="callVerify">Call me to verify order</label>
        </div>
        <button type="submit" id="submit_order" class="btn btn-primary">Submit Order</button>
    </form>
    </section>
{% endblock %}

wsp/wspsite/templates/partials/pricing.html
{% extends "home.html" %}
{% block content %}
<section>
  
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal">Pricing</h1>
        <p class="fs-5 text-muted">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
      </div>
 
      <div class="row row-cols-1 row-cols-md-3 mb-3 text-center m-5">
        <form action="/small_order" method="post">
          {% csrf_token %}
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Small Business</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">$12<small class="text-muted fw-light">/per case</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>4 Case Minimum</li>
                <li>5% discount per case</li>
                <li>Email support</li>
                <li>Help center access</li>
              </ul>
              <input type="submit" id="small_order" name="small_order" class="w-100 btn btn-lg btn-primary" />
            </div>
          </div>
        </div>
      </form>
      <form action="/med_order" method="post">
        {% csrf_token %}
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Medium Business</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">$11<small class="text-muted fw-light">/per case</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>12 Case Minimum</li>
                <li>15% discount per case</li>
                <li>Priority email support</li>
                <li>Help center access</li>
              </ul>
              <input type="submit" id="med_order" name="med_order" class="w-100 btn btn-lg btn-primary" />
            </div>
          </div>
        </div>
      </form>
      <form action="/ent_order" method="post">
        {% csrf_token %}
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Enterprise</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">$9<small class="text-muted fw-light">/per case</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>25 Case Minimum</li>
                <li>30% discount per case</li>
                <li>Phone and email support</li>
                <li>Help center access</li>
              </ul>
              <input type="submit" id="ent_order" name="ent_order" class="w-100 btn btn-lg btn-primary" />
            </div>
          </div>
        </div>
      </form>
    </div>
</section>
{% endblock %}

wsp/wspsite/templates/partials/productinfo.html
{% extends "home.html" %}
{% block content %}
<section>
    <main>
        <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
          <div class="col-md-12">
            <h1 class="display-4 fw-normal">Product Information</h1>
            <p class="lead fw-normal">Experience the refreshing twist on hydration with our Watermelon Seltzer. Shop now and add a splash of summer to your day!
            </p>
            <a href="/pricing" class="btn btn-outline-secondary" href="#">Find out more about Pricing!</a>
          </div>
          <div class="product-device shadow-sm d-none d-md-block"></div>
          <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
        </div>

        <div class="d-sm-flex flex-sm-equal w-100 my-md-3 ps-md-3">
          <div class="bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
            <div class="my-3 py-3">
              <h2 class="display-5">Healthy Hydration
              </h2>
              <p class="lead">We firmly believe that hydration should never be mundane. That’s why our Watermelon Seltzer is delicious and a healthy choice. It's free from added sugars, artificial flavors, and preservatives, making it a guilt-free way to quench your thirst and replenish your body.
              </p>
            </div>
            {% load static %}
            <div class="d-flex justify-content-end">
                <img src="{% static 'images/marketingimg2.jpg' %}" alt="" width="100%" style="border-radius: 5%">
            </div>
          </div>
          <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
            <div class="my-3 p-3">
              <h2 class="display-5">Sustainability Matters
              </h2>
              <p class="lead">We’re committed to doing our part for the planet. Our Watermelon Seltzer is packaged in recyclable cans, and we source our ingredients sustainably. When you choose our seltzer, you’re making a choice that’s good for you and the earth.
              </p>
            </div>
            {% load static %}
            <div class="d-flex justify-content-end">
                <img src="{% static 'images/marketingimg1.jpg' %}" alt="" width="100%" style="border-radius: 5%">
            </div>
          </div>
        </div>

        <div class="d-sm-flex flex-sm-equal w-100 my-md-3 ps-md-3">
          <div class="bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
            <div class="my-3 py-3">
              <h2 class="display-5">Perfect for Any Occasion
              </h2>
              <p class="lead">Whether you’re hosting a party, looking for a refreshing post-workout drink, or want to unwind after a long day, our Watermelon Seltzer is the perfect choice. Enjoy it from the can, over ice, or as a mixer in your favorite cocktail.
              </p>
            </div>
            {% load static %}
            <div class="d-flex justify-content-end">
                <img src="{% static 'images/marketingimg3.jpg' %}" alt="" width="100%" style="border-radius: 5%">
            </div>
          </div>
        </div>
      </main>
{% endblock %}
</section>